import type { Preset } from "@/lib/types";

/**
 * 기본 프리셋.
 *
 * 시작점이지 정답이 아니다. 화면에서 복제·수정·추가하면 data/presets.json에 쌓인다.
 * 여기 배열에 항목을 더하면 다음 실행 때 새 기본 프리셋으로 합류한다
 * (이미 있는 id는 덮어쓰지 않는다).
 */

type Seed = Omit<Preset, "id" | "createdAt" | "updatedAt" | "builtin">;

/** 모든 이미지 프롬프트 뒤에 공통으로 붙는 문구. */
const COMMON_SUFFIX =
  "Single still frame, no panels, no overlaid subtitles or title cards. No watermark. If any text appears, it must be Korean only.";

export const DEFAULT_PRESETS: Array<{ id: string } & Seed> = [
  /**
   * 롱폼 경제 다큐.
   *
   * 아래 숫자는 짐작이 아니라 **실제 원고에서 잰 값**이다. eatconomy 채널의
   * 9,415자짜리 대본을 넣어 재보니 이렇게 나왔다.
   *   - 27분 3초 (5.8자/초 기준)
   *   - 구간 14개 — 훅 1 · 인트로 1 · 파트 8 · 행동유도 2 · 클로징 2
   *   - 자막 줄 455개, 길이 중앙값 21자 (25% 16자 / 75% 25자 / 최대 34자)
   *
   * 기존 '화이트보드 · 다큐 해설'은 목표 180초에 파트 4개라 롱폼에 전혀 안 맞았다.
   * 화풍과 장면 간격은 그쪽과 같게 두었다 — 그림체는 이미 맞고, 간격도 레퍼런스가
   * 같은 값(훅+인트로 8~13초 / 파트 12~22초)을 쓰고 있었다.
   */
  {
    id: "longform-doc",
    name: "롱폼 · 경제 다큐 해설",
    description:
      "20~30분 손그림 해설. 사건을 파트로 나눠 근거를 쌓고 마지막에 뒤집는다.",
    aspect: "16:9",
    fps: 30,
    // 실측 27분 3초. ±15% 허용이므로 23~31분이 목표 범위가 된다.
    targetDurationSec: 1620,
    script: {
      language: "ko",
      persona: "근거를 먼저 대고 결론을 내리는 해설자",
      tone: "차분한 존댓말. 한 문장에 한 가지만.",
      // 실측 8개.
      partCount: 8,
      // 실측 중앙 21자 / 75% 25자. 34자짜리도 있지만 여섯 줄뿐이라 상한은 30으로 둔다.
      charsPerLine: { min: 14, max: 30 },
      avoid: ["단정적 예측", "감정적 수사", "출처 불명 수치", "영어 병기"],
    },
    intervals: {
      hookIntro: { min: 8, max: 13 },
      part: { min: 12, max: 22 },
      closing: { min: 12, max: 22 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Hand-drawn minimalist sketch style, whiteboard animation aesthetic, clean ink linework with soft watercolor wash, muted sepia and earth-tone palette, warm aged paper texture background, simple stick-figure characters with round heads, dot eyes and contextual clothing, detailed architectural backgrounds in loose watercolor with isometric perspective, editorial documentary illustration feel, one key focal object per scene in vivid saturated color as a dramatic spotlight against the muted sepia",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, photorealistic, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual",
      model: "",
      voiceId: "",
      speed: 1.0,
      pitch: 0,
      leadSilenceMs: 400,
      tailSilenceMs: 700,
      gapMs: 200,
      sectionGapMs: 500,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      // 레퍼런스에서 '적게'를 고르면 나오는 값이다.
      maxCharsPerLine: 20,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.45,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "dissolve", "zoomIn", "panRight", "zoomOut", "panLeft"],
    },
  },
  /*
   * 아래 14종은 코덱스로 유튜브 포맷을 병렬 리서치해 만든 것이다.
   * 길이·파트 수·자막 글자수·장면 간격은 각 포맷에서 실제로 통용되는 값을 찾아 넣었고,
   * 근거 도메인은 리서치 원본(scratchpad/research)에 남겼다.
   *
   * 화풍 접두부(prefix)는 리서치가 한국어 한 문장으로만 줬으므로 영문 프롬프트로는
   * 내가 옮겼다. 그림체는 눈으로 확인해야 하는 값이라 아직 미검증이다.
   *
   * 쉼과 전환 길이는 포맷의 속도에서 끌어냈다 — 세로/짧은 포맷은 무음을 줄이고
   * 전환을 빠르게, 롱폼은 반대로. 빠른 포맷에 긴 무음을 두면 흐름이 죽는다.
   */
  {
    id: "issue-context-explainer",
    name: "미들폼 · 이슈 맥락 해설",
    description: "쟁점의 배경과 영향을 근거로 풀어낸다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 720,
    script: {
      language: "ko",
      persona: "자료를 검증해 맥락과 파장을 설명하는 분석자다.",
      tone: "차분한 존댓말로 사실과 해석을 분리한다.",
      partCount: 4,
      charsPerLine: { min: 12, max: 16 },
      avoid: ["출처 없는 단정", "정파적 선동", "긴 채널 인트로", "같은 화면 반복"],
    },
    intervals: {
      hookIntro: { min: 5, max: 10 },
      part: { min: 10, max: 20 },
      closing: { min: 12, max: 20 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Restrained editorial news look, natural documentary photography, muted neutral palette with one signal colour, even daylight, clean map and chart motifs worked into the frame, broadsheet newspaper feel",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 250, tailSilenceMs: 500, gapMs: 150, sectionGapMs: 350,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 16,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.3,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "zoomIn", "panRight", "dissolve"],
    },
  },
  {
    id: "comparison-curation",
    name: "미들폼 · 비교 큐레이션",
    description: "제품과 자료를 기준별로 비교해 추천한다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 600,
    script: {
      language: "ko",
      persona: "직접 검토한 대상을 기준별로 판정하는 실용 리뷰어다.",
      tone: "장단점을 짧고 구체적으로 말하며 결론을 미루지 않는다.",
      partCount: 5,
      charsPerLine: { min: 10, max: 16 },
      avoid: ["협찬 사실 은폐", "근거 없는 순위", "사양표 낭독", "모든 대상을 칭찬하기"],
    },
    intervals: {
      hookIntro: { min: 3, max: 5 },
      part: { min: 5, max: 8 },
      closing: { min: 6, max: 10 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Crisp product-magazine look, high-key studio photography on a seamless backdrop, one bright saturated accent against neutral grey, soft large-source light with clean specular highlights, tidy side-by-side arrangements",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 250, tailSilenceMs: 500, gapMs: 150, sectionGapMs: 350,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 16,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.3,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "zoomIn", "panRight", "dissolve"],
    },
  },
  {
    id: "step-by-step-tutorial",
    name: "미들폼 · 따라하기 튜토리얼",
    description: "하나의 과제를 단계별 시연으로 완성한다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 600,
    script: {
      language: "ko",
      persona: "초보자의 화면과 실수를 예상하며 안내하는 실무 강사다.",
      tone: "짧은 명령형 존댓말로 한 번에 한 동작만 설명한다.",
      partCount: 5,
      charsPerLine: { min: 10, max: 16 },
      avoid: ["결과 없는 긴 서론", "단계 생략", "작은 화면 글씨", "검증하지 않은 단축키", "과도한 화면 확대"],
    },
    intervals: {
      hookIntro: { min: 5, max: 8 },
      part: { min: 10, max: 20 },
      closing: { min: 8, max: 15 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Clean instructional manual look, flat vector illustration with soft drop shadows, bright white ground, a single accent colour marking the current step, oversized simple icons and callout circles, calm and uncluttered",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 250, tailSilenceMs: 500, gapMs: 150, sectionGapMs: 350,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 16,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.3,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "zoomIn", "panRight", "dissolve"],
    },
  },
  {
    id: "company-deep-dive",
    name: "롱폼 · 기업해부다큐",
    description: "한 기업의 성장과 위기를 서사로 추적한다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 1800,
    script: {
      language: "ko",
      persona: "기업의 전략과 숫자를 추적하는 비즈니스 탐사자다.",
      tone: "흥미로운 서사를 유지하되 평가와 사실을 분리한다.",
      partCount: 6,
      charsPerLine: { min: 12, max: 16 },
      avoid: ["기업 홍보 문구", "근거 없는 음모론", "현재와 과거 실적 혼용", "창업자 영웅화"],
    },
    intervals: {
      hookIntro: { min: 2, max: 4 },
      part: { min: 5, max: 8 },
      closing: { min: 6, max: 9 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Polished corporate documentary look, clean editorial photography and product renders, deep navy and warm grey palette, soft studio key light with a subtle rim, glass-and-steel office interiors, restrained data overlays, premium business magazine feel",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 400, tailSilenceMs: 700, gapMs: 200, sectionGapMs: 500,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 16,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.45,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "dissolve", "zoomIn", "panRight", "zoomOut", "panLeft"],
    },
  },
  {
    id: "case-reconstruction",
    name: "롱폼 · 사건재구성",
    description: "실제 사건의 시간선과 단서를 재구성한다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 2100,
    script: {
      language: "ko",
      persona: "확인된 기록만 따라가는 침착한 사건 내레이터다.",
      tone: "긴장감은 유지하되 선정적 표현과 단정을 삼간다.",
      partCount: 7,
      charsPerLine: { min: 10, max: 16 },
      avoid: ["피해자 신상 노출", "잔혹 장면 반복", "미확인 범인 지목", "허구를 사실처럼 제시", "과도한 효과음"],
    },
    intervals: {
      hookIntro: { min: 2, max: 5 },
      part: { min: 6, max: 10 },
      closing: { min: 7, max: 12 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Investigative documentary look, desaturated archival photography, cold blue-grey palette with a single amber accent, hard directional light and deep shadow, fine grain and slight vignette, evidence-board and timeline motifs, sombre forensic mood",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 400, tailSilenceMs: 700, gapMs: 200, sectionGapMs: 500,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 16,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.45,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "dissolve", "zoomIn", "panRight", "zoomOut", "panLeft"],
    },
  },
  {
    id: "issue-hook",
    name: "쇼츠 · 이슈 훅형",
    description: "화제의 핵심과 반전을 빠르게 전달한다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 20,
    script: {
      language: "ko",
      persona: "이슈의 결정적 장면을 먼저 포착한 해설자다.",
      tone: "짧고 단정하게 말하되 확인된 사실과 해석을 구분한다.",
      partCount: 2,
      charsPerLine: { min: 7, max: 12 },
      avoid: ["느린 인사말", "출처 없는 단정", "과장된 공포 조장", "같은 화면 반복"],
    },
    intervals: {
      hookIntro: { min: 1, max: 2 },
      part: { min: 2, max: 3 },
      closing: { min: 1, max: 2 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "High-contrast news-graphic look, bold saturated red and black over documentary photography, hard light, heavy vignette, urgent broadcast-alert energy, vertical composition with one clear centre subject",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 12,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "numbered-list",
    name: "쇼츠 · N가지 리스트",
    description: "한 주제를 번호별 핵심 정보로 정리한다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 45,
    script: {
      language: "ko",
      persona: "복잡한 정보를 빠르게 선별해 주는 큐레이터다.",
      tone: "번호를 먼저 말하고 각 항목은 한 문장으로 끝낸다.",
      partCount: 5,
      charsPerLine: { min: 8, max: 14 },
      avoid: ["항목 수 숨기기", "항목 간 내용 중복", "긴 배경 설명", "복수 행동 유도"],
    },
    intervals: {
      hookIntro: { min: 1, max: 3 },
      part: { min: 5, max: 7 },
      closing: { min: 2, max: 3 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Bold infographic look, flat geometric shapes, oversized numerals used as design elements, bright primary palette on solid colour blocks, thick clean outlines, playful and instantly readable, vertical composition",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 14,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "knowledge-bite",
    name: "쇼츠 · 지식 한 토막",
    description: "질문 하나를 짧은 원리와 사례로 푼다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 30,
    script: {
      language: "ko",
      persona: "어려운 개념을 일상 사례로 설명하는 지식 해설자다.",
      tone: "질문·원리·사례 순서로 쉽고 정확하게 설명한다.",
      partCount: 3,
      charsPerLine: { min: 8, max: 14 },
      avoid: ["전문용어 남발", "여러 개념 혼합", "근거 없는 상식", "긴 구독 요청"],
    },
    intervals: {
      hookIntro: { min: 1, max: 3 },
      part: { min: 3, max: 5 },
      closing: { min: 2, max: 4 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Friendly educational animation look, simple 2D diagrams with rounded shapes, warm pastel palette, soft even light, one object in clear close-up per frame, chalk-and-paper texture, curious and approachable",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 14,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "flash-deal-short",
    name: "쇼핑 · 초특가 딜 쇼츠",
    description: "가격 하락과 할인 조건을 즉시 알려준다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 15,
    script: {
      language: "ko",
      persona: "가격을 매일 추적하는 생활형 딜 큐레이터다.",
      tone: "결론부터 짧게 말하고 가격과 조건은 숫자로 읽는다.",
      partCount: 2,
      charsPerLine: { min: 6, max: 11 },
      avoid: ["가짜 품절 임박", "정가만 강조하기", "할인 조건 누락", "제휴 사실 숨기기"],
    },
    intervals: {
      hookIntro: { min: 1, max: 2 },
      part: { min: 1, max: 3 },
      closing: { min: 2, max: 3 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "High-impact commerce look, product close-up on a bold solid colour ground, hard punchy light with a strong specular highlight, hot red and yellow accents, price-tag and starburst motifs, vertical composition",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 11,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "ugc-product-demo",
    name: "쇼핑 · 실사용 리뷰 쇼츠",
    description: "문제를 제시하고 제품 효과를 직접 검증한다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 45,
    script: {
      language: "ko",
      persona: "직접 구매해 써본 현실적인 소비자 리뷰어다.",
      tone: "친근하게 말하되 장점과 한계를 구체적으로 구분한다.",
      partCount: 3,
      charsPerLine: { min: 7, max: 11 },
      avoid: ["효과 과장", "사용 장면 생략", "단점 은폐", "무관한 상품 태그", "제휴 고지 누락"],
    },
    intervals: {
      hookIntro: { min: 1, max: 3 },
      part: { min: 2, max: 3 },
      closing: { min: 2, max: 4 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Authentic smartphone-shot look, handheld framing, ordinary home or desk surroundings, natural window light with a mild colour cast, slight lens softness, hands entering frame to demonstrate, unpolished and believable, vertical composition",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 11,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "affiliate-buying-guide",
    name: "쇼핑 · 구매가이드 리뷰",
    description: "제품을 비교 검증해 구매 대상을 판별한다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 480,
    script: {
      language: "ko",
      persona: "사양과 실사용 데이터를 함께 검증하는 전문 리뷰어다.",
      tone: "판단 기준을 먼저 밝히고 근거와 추천 대상을 명료하게 말한다.",
      partCount: 4,
      charsPerLine: { min: 10, max: 16 },
      avoid: ["스펙표 낭독", "경쟁 제품 비방", "검증 없는 단정", "모든 시청자에게 추천", "제휴 고지 누락"],
    },
    intervals: {
      hookIntro: { min: 3, max: 5 },
      part: { min: 5, max: 10 },
      closing: { min: 5, max: 8 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Clean review-studio look, product on a neutral seamless backdrop, soft two-source lighting with a gentle shadow, calm grey-and-wood palette, measured test-bench arrangements, trustworthy and understated",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 250, tailSilenceMs: 500, gapMs: 150, sectionGapMs: 350,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 16,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.3,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "zoomIn", "panRight", "dissolve"],
    },
  },
  {
    id: "clip-highlight-compilation",
    name: "짜집기 · 클립 하이라이트",
    description: "주제별 핵심 클립을 해설과 함께 엮는다.",
    aspect: "16:9",
    fps: 30,
    targetDurationSec: 600,
    script: {
      language: "ko",
      persona: "맥락과 선정 이유를 덧붙이는 전문 큐레이터다.",
      tone: "짧고 단정하게 설명하며 클립보다 앞서 말하지 않는다.",
      partCount: 8,
      charsPerLine: { min: 14, max: 23 },
      avoid: ["무해설 원본 재업로드", "출처와 사용권 미확인", "긴 로고 인트로", "비슷한 클립 반복", "충격 장면의 과도한 사용"],
    },
    intervals: {
      hookIntro: { min: 1, max: 3 },
      part: { min: 3, max: 7 },
      closing: { min: 4, max: 8 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Punchy highlight-reel look, vivid documentary photography, high saturation and contrast, bold rank-badge and bracket motifs in a single accent colour, energetic sports-broadcast feel",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 250, tailSilenceMs: 500, gapMs: 150, sectionGapMs: 350,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.08,
      position: "bottom",
      marginRatio: 0.1,
      maxCharsPerLine: 23,
    },
    effects: {
      defaultEffect: "fade",
      transitionSec: 0.3,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.08 },
      rotate: true,
      rotation: ["fade", "zoomIn", "panRight", "dissolve"],
    },
  },
  {
    id: "captioned-incident-recap",
    name: "짜집기 · 자막 사건정리",
    description: "사건의 발단부터 결말까지 자막으로 압축한다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 60,
    script: {
      language: "ko",
      persona: "확인된 사실만 시간순으로 정리하는 사건 브리퍼다.",
      tone: "짧은 문장으로 긴장감을 유지하되 단정적 추측은 피한다.",
      partCount: 5,
      charsPerLine: { min: 7, max: 13 },
      avoid: ["미확인 사실 단정", "낚시성 왜곡", "피해자 신상 노출", "출처 없는 화면", "읽기 어려운 장문 자막"],
    },
    intervals: {
      hookIntro: { min: 1, max: 2 },
      part: { min: 2, max: 4 },
      closing: { min: 2, max: 4 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Stark recap look, desaturated documentary imagery on a dark ground, one cold accent colour, timeline and marker motifs, heavy contrast so it stays legible small, vertical composition, tense and matter-of-fact",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 13,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "reaction-short-montage",
    name: "짜집기 · 리액션 숏모음",
    description: "여러 사람의 반응과 결정적 순간을 빠르게 잇는다.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 30,
    script: {
      language: "ko",
      persona: "반응의 차이와 재미를 짚어주는 유쾌한 진행자다.",
      tone: "감탄은 짧게 쓰고 매 반응마다 새 관찰을 덧붙인다.",
      partCount: 4,
      charsPerLine: { min: 7, max: 12 },
      avoid: ["무언 리액션만 나열", "원본 음원 장시간 사용", "과장된 가짜 반응", "동일 장면 반복", "화면을 가리는 자막"],
    },
    intervals: {
      hookIntro: { min: 1, max: 2 },
      part: { min: 1, max: 3 },
      closing: { min: 2, max: 3 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "Split-frame reaction look, vivid candid photography, exaggerated close-ups of faces and hands, bright high-energy palette, comic pop-out and burst motifs, fast and playful, vertical composition",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, cluttered composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual", model: "", voiceId: "", speed: 1.0, pitch: 0,
      leadSilenceMs: 120, tailSilenceMs: 300, gapMs: 70, sectionGapMs: 180,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 13,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.1,
      position: "center",
      marginRatio: 0.18,
      maxCharsPerLine: 12,
    },
    effects: {
      defaultEffect: "zoomIn",
      transitionSec: 0.18,
      kenBurns: { enabled: true, scaleFrom: 1.0, scaleTo: 1.12 },
      rotate: true,
      rotation: ["zoomIn", "whiteFlash", "zoomOut", "panLeft"],
    },
  },
  {
    id: "emotional-vlog",
    name: "감성 · 브이로그",
    description: "세로 60초. 느린 호흡, 여백 많은 화면, 담담한 톤.",
    aspect: "9:16",
    fps: 30,
    targetDurationSec: 60,
    script: {
      language: "ko",
      persona: "혼잣말하듯 담담하게 이야기하는 화자",
      tone: "느린 존댓말. 형용사보다 장면을 말한다.",
      partCount: 3,
      charsPerLine: { min: 12, max: 24 },
      avoid: ["과장된 감탄", "설명조", "정보 나열"],
    },
    intervals: {
      hookIntro: { min: 4, max: 7 },
      part: { min: 6, max: 12 },
      closing: { min: 6, max: 12 },
    },
    image: {
      provider: "manual",
      model: "",
      prefix:
        "35mm film photograph, visible grain, soft diffused window light, desaturated pastel palette, generous negative space, quiet everyday scene, natural candid framing",
      suffix: COMMON_SUFFIX,
      negativePrompt: "text, watermark, harsh flash, crowded composition",
    },
    video: { defaultMode: "image", provider: "manual", model: "" },
    tts: {
      provider: "manual",
      model: "",
      voiceId: "",
      speed: 0.92,
      pitch: -1,
      leadSilenceMs: 600,
      tailSilenceMs: 900,
      gapMs: 320,
      sectionGapMs: 700,
    },
    caption: {
      enabled: true,
      fontFamily: "Pretendard",
      fontSize: 10,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 0.06,
      position: "bottom",
      marginRatio: 0.12,
      maxCharsPerLine: 18,
    },
    effects: {
      defaultEffect: "dissolve",
      transitionSec: 0.7,
      kenBurns: { enabled: true, scaleFrom: 1.06, scaleTo: 1.0 },
      rotate: true,
      rotation: ["dissolve", "fade", "blur", "zoomOut"],
    },
  },
];
